In [22]:
import numpy as np
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler


In [23]:

# ------------------------------
# GRNN Implementation
# ------------------------------
class GRNN:
    def __init__(self, sigma=0.1):
        self.sigma = sigma
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)

    def predict(self, X):
        X = np.array(X)
        y_pred = []
        for x in X:
            diff = self.X_train - x
            sq_dist = np.sum(diff**2, axis=1)
            weights = np.exp(-sq_dist / (2* self.sigma**2))
            y_hat = np.sum(weights * self.y_train.ravel()) / np.sum(weights)
            y_pred.append(y_hat)
        return np.array(y_pred)


In [24]:

# ------------------------------
# Load dataset
# ------------------------------
dataset = datasets.load_diabetes()


In [25]:
dataset.data


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [26]:
dataset.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [27]:

X = dataset.data
y = dataset.target.reshape(-1, 1)


# Train/test split
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Scale input features
x_scaler = MinMaxScaler()
x_train = x_scaler.fit_transform(x_train)
x_test = x_scaler.transform(x_test)

# Scale target values
y_scaler = MinMaxScaler()
y_train = y_scaler.fit_transform(y_train)
y_test = y_scaler.transform(y_test)


In [28]:
y_train

array([[0.57009346],
       [0.73520249],
       [0.47975078],
       [0.7258567 ],
       [0.73831776],
       [0.08099688],
       [0.66043614],
       [0.14330218],
       [0.35514019],
       [0.75700935],
       [0.13707165],
       [0.90965732],
       [0.69781931],
       [0.40186916],
       [0.52024922],
       [0.2834891 ],
       [0.17445483],
       [0.30218069],
       [0.72897196],
       [0.51713396],
       [0.8317757 ],
       [0.09345794],
       [0.25545171],
       [0.57632399],
       [0.20560748],
       [0.71028037],
       [0.18691589],
       [0.70716511],
       [0.105919  ],
       [0.16510903],
       [0.54517134],
       [0.16510903],
       [0.68535826],
       [0.46728972],
       [0.0529595 ],
       [0.31775701],
       [0.08722741],
       [0.21495327],
       [0.24610592],
       [0.54205607],
       [0.74766355],
       [0.79750779],
       [0.69470405],
       [0.72274143],
       [0.59190031],
       [0.86604361],
       [0.4517134 ],
       [0.105

In [15]:

# ------------------------------
# Train GRNN
# ------------------------------
grnn = GRNN(sigma=0.3)   # You can tune sigma
grnn.fit(x_train, y_train)


In [29]:

# Predict
y_pred = grnn.predict(x_test)


In [30]:
y_pred

array([0.40322524, 0.4069467 , 0.41710608, 0.59945455, 0.37129416,
       0.33672012, 0.59702   , 0.49083164, 0.24546722, 0.29772919,
       0.31287881, 0.35096815, 0.27569832, 0.4988654 , 0.27932306,
       0.28008561, 0.53700777, 0.58638893, 0.39365146, 0.51285003,
       0.43636605, 0.30113788, 0.27603984, 0.46069104, 0.36813743,
       0.39664719, 0.43921958, 0.41205035, 0.25337192, 0.34512838,
       0.42259112, 0.32908807, 0.33293147, 0.43403891, 0.43201853,
       0.4643629 , 0.32791595, 0.36072249, 0.4272312 , 0.25762379,
       0.28563338, 0.30876021, 0.3685503 , 0.42735212, 0.43130364,
       0.2713386 , 0.29338484, 0.29280126, 0.25990965, 0.36355621,
       0.33445726, 0.28648364, 0.34495951, 0.30931336, 0.49201267,
       0.36170028, 0.31662365, 0.45198905, 0.31254996, 0.25426575,
       0.452484  , 0.42742724, 0.26087503, 0.30877565, 0.34553934,
       0.46699069, 0.45367236, 0.4004928 , 0.31623792, 0.33116455,
       0.37791795, 0.48916651, 0.55343209, 0.30436745, 0.27631

In [31]:

# ------------------------------
# Evaluation
# ------------------------------
mse = mean_squared_error(y_test, y_pred)
print("Test MSE:", mse)


Test MSE: 0.03182373168819544
